# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/Zynq_interrupt_system/Zynq_interrupt_system.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Zynq_interrupt_system || ORIG_REF_NAME==Zynq_interrupt_system} -quiet] -quiet

# IP: bd/Zynq_interrupt_system/ip/Zynq_interrupt_system_processing_system7_0_0/Zynq_interrupt_system_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Zynq_interrupt_system_processing_system7_0_0 || ORIG_REF_NAME==Zynq_interrupt_system_processing_system7_0_0} -quiet] -quiet

# IP: bd/Zynq_interrupt_system/ip/Zynq_interrupt_system_axi_gpio_0_0/Zynq_interrupt_system_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Zynq_interrupt_system_axi_gpio_0_0 || ORIG_REF_NAME==Zynq_interrupt_system_axi_gpio_0_0} -quiet] -quiet

# IP: bd/Zynq_interrupt_system/ip/Zynq_interrupt_system_axi_gpio_1_0/Zynq_interrupt_system_axi_gpio_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Zynq_interrupt_system_axi_gpio_1_0 || ORIG_REF_NAME==Zynq_interrupt_system_axi_gpio_1_0} -quiet] -quiet

# IP: bd/Zynq_interrupt_system/ip/Zynq_interrupt_system_ps7_0_axi_periph_0/Zynq_interrupt_system_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Zynq_interrupt_system_ps7_0_axi_periph_0 || ORIG_REF_NAME==Zynq_interrupt_system_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/Zynq_interrupt_system/ip/Zynq_interrupt_system_rst_ps7_0_100M_0/Zynq_interrupt_system_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Zynq_interrupt_system_rst_ps7_0_100M_0 || ORIG_REF_NAME==Zynq_interrupt_system_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/Zynq_interrupt_system/ip/Zynq_interrupt_system_xbar_0/Zynq_interrupt_system_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Zynq_interrupt_system_xbar_0 || ORIG_REF_NAME==Zynq_interrupt_system_xbar_0} -quiet] -quiet

# IP: bd/Zynq_interrupt_system/ip/Zynq_interrupt_system_axi_timer_0_0/Zynq_interrupt_system_axi_timer_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Zynq_interrupt_system_axi_timer_0_0 || ORIG_REF_NAME==Zynq_interrupt_system_axi_timer_0_0} -quiet] -quiet

# IP: bd/Zynq_interrupt_system/ip/Zynq_interrupt_system_xlconcat_0_0/Zynq_interrupt_system_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Zynq_interrupt_system_xlconcat_0_0 || ORIG_REF_NAME==Zynq_interrupt_system_xlconcat_0_0} -quiet] -quiet

# IP: bd/Zynq_interrupt_system/ip/Zynq_interrupt_system_axi_gpio_2_0/Zynq_interrupt_system_axi_gpio_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Zynq_interrupt_system_axi_gpio_2_0 || ORIG_REF_NAME==Zynq_interrupt_system_axi_gpio_2_0} -quiet] -quiet

# IP: bd/Zynq_interrupt_system/ip/Zynq_interrupt_system_auto_pc_0/Zynq_interrupt_system_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Zynq_interrupt_system_auto_pc_0 || ORIG_REF_NAME==Zynq_interrupt_system_auto_pc_0} -quiet] -quiet

# XDC: bd/Zynq_interrupt_system/Zynq_interrupt_system_ooc.xdc
